name: Terraform CI
on:
  push:
    branches:
      - main
env:
  ORGANIZATION: "M2I"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Hello World script
        run: echo "Hello,world!"

      - name: GET ID Terraform app.terraform.io
        uses: sarathkrish/invoke-terraform-run-api@v1.0   
        with:  
          workSpaceName: terraform
          organizationName: ${{ env.ORGANIZATION }}
          terraformToken: ${{ secrets.TERRAFORM_TOKEN }}
          terraformHost: 'app.terraform.io'
          isDestroy: false
          message: 'GitHub Actions'

      - name: using HashiCorp
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}
