name: Terraform CI
on:
  push:
    branches:
      - main
      
env:
  ORGANIZATION: "M2I"
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: starting by checkout
      uses: actions/checkout@v4

    - name: GET ID Terraform app.terraform.io
      uses: sarathkrish/invoke-terraform-run-api@v1.0   
      with:  
        workSpaceName: terraform
        organizationName: ${{ env.ORGANIZATION }}
        terraformToken: ${{ secrets.TERRAFORM_TOKEN }}
        terraformHost: 'app.terraform.io'
        isDestroy: false
        message: 'GitHub Actions'
          
    - name: Using hashicoorp terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: terraform workspace show
      run: terraform workspace show
        
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: false
      
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
